spring:
  application.name: mybnb
  datasource:
    jpa:
      properties:
        hibernate:
          format_sql: true
          show_sql: true

---
spring:
  profiles.active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybnb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

---
spring:
  profiles.active: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/mybnb
    username: root
    password:

  jpa.hibernate.ddl-auto: create
  h2.console.enabled: true
logging.level.org.hibernate.type.descriptor.sql: trace